### ISSUE TITLE
Inconsistencies between software and user guide

### ISSUE THREAD

**Issue by lingyanhao** [cs2103-ay1819S2-w11-2/main#123]
The current set of commands we support does not match the user guide.
Let's all be clear about what commands we want to support.

Present in user guide, not in software:
`listIngredients`
all recipe related functions
`viewBooking` (i will roll this out soon)
`shiftStaff`
`setShift`
the entire `overall` section

Present in software, not in user guide:
`select` (does anyone need this?)
`clear`  (looks like a useful feature, we might want to keep this)
`find` (our current `listMembers` function combines list and find, looks like we don't need it)
`undo`, `redo`
`viewStats` (should document this)

Commands that need renaming:
`cancelBooking` -> `deleteBooking`
`depleteIngredient` -> `consumeIngredient`

**Comment by lingyanhao** [comment]
Renamed `cancelBooking` and `deleteBooking`
Temporarily placed `undo`, `redo` and `clear` commands to the overall section.

**Comment by hiyingnn** [comment]
listIngredients implementation, and depleteIngredient renaming in UG in #127

**Comment by hiyingnn** [comment]
Should we also standardise it as list____ as naming convention . viewBooking --> listBookings, or does  viewBooking have a different function? @lingyanhao

**Comment by lingyanhao** [comment]
ok rename to `listBookings`

**Comment by hiyingnn** [comment]
- Marked `overall` section as (coming in v2.0) #142 

- Present in software, not in user guide:
I think we should keep `clear`, `undo` and `redo`,  I will edit the UG accordingly. The rest:  `select`, `find` is similar and already implemented in list, I think can remove.

**Comment by lingyanhao** [comment]
Still need to remove `find` and `select` commands

@hiyingnn

**Comment by hiyingnn** [comment]
removed find and select commands #198 
removed list command #202
