### ISSUE TITLE
Refactor project structure

### ISSUE THREAD

**Issue by zj-cs2103** [cs2103-ay1819S2-w11-2/main#139]
Currently, the project structure is quite 'flat', e.g. all the parsers are in the same package.
Should put all classes related to the same feature in separate packages, e.g. all the member related parsers in one package.

**Comment by zj-cs2103** [comment]
@limli @hiyingnn yanhao and I have done ours, remember to do.

**Comment by hiyingnn** [comment]
done in #202

**Comment by limli** [comment]
done also
